# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitledversion2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 299)
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rezultBoaton = QtWidgets.QLabel(self.centralwidget)
        self.rezultBoaton.setGeometry(QtCore.QRect(0, 0, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rezultBoaton.setFont(font)
        self.rezultBoaton.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.rezultBoaton.setObjectName("rezultBoaton")
        self.zero0 = QtWidgets.QPushButton(self.centralwidget)
        self.zero0.setGeometry(QtCore.QRect(0, 190, 111, 61))
        self.zero0.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.zero0.setObjectName("zero0")
        self.ButtonEqual = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonEqual.setGeometry(QtCore.QRect(110, 190, 161, 61))
        self.ButtonEqual.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.ButtonEqual.setObjectName("ButtonEqual")
        self.batn1 = QtWidgets.QPushButton(self.centralwidget)
        self.batn1.setGeometry(QtCore.QRect(0, 40, 91, 51))
        self.batn1.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.batn1.setObjectName("batn1")
        self.number2 = QtWidgets.QPushButton(self.centralwidget)
        self.number2.setGeometry(QtCore.QRect(90, 40, 91, 51))
        self.number2.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number2.setObjectName("number2")
        self.number3 = QtWidgets.QPushButton(self.centralwidget)
        self.number3.setGeometry(QtCore.QRect(180, 40, 91, 51))
        self.number3.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number3.setObjectName("number3")
        self.number4 = QtWidgets.QPushButton(self.centralwidget)
        self.number4.setGeometry(QtCore.QRect(0, 90, 91, 51))
        self.number4.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number4.setObjectName("number4")
        self.number5 = QtWidgets.QPushButton(self.centralwidget)
        self.number5.setGeometry(QtCore.QRect(90, 90, 91, 51))
        self.number5.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number5.setObjectName("number5")
        self.number6 = QtWidgets.QPushButton(self.centralwidget)
        self.number6.setGeometry(QtCore.QRect(180, 90, 91, 51))
        self.number6.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number6.setObjectName("number6")
        self.number27 = QtWidgets.QPushButton(self.centralwidget)
        self.number27.setGeometry(QtCore.QRect(0, 140, 91, 51))
        self.number27.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number27.setObjectName("number27")
        self.number8 = QtWidgets.QPushButton(self.centralwidget)
        self.number8.setGeometry(QtCore.QRect(90, 140, 91, 51))
        self.number8.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number8.setObjectName("number8")
        self.number9 = QtWidgets.QPushButton(self.centralwidget)
        self.number9.setGeometry(QtCore.QRect(180, 140, 91, 51))
        self.number9.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.number9.setObjectName("number9")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(270, 40, 61, 51))
        self.add.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.add.setObjectName("add")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(270, 90, 61, 51))
        self.minus.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.minus.setObjectName("minus")
        self.multi = QtWidgets.QPushButton(self.centralwidget)
        self.multi.setGeometry(QtCore.QRect(270, 140, 61, 51))
        self.multi.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.multi.setObjectName("multi")
        self.div = QtWidgets.QPushButton(self.centralwidget)
        self.div.setGeometry(QtCore.QRect(270, 190, 61, 61))
        self.div.setStyleSheet("background-color: rgb(237, 212, 0);")
        self.div.setObjectName("div")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.addFafunction()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rezultBoaton.setText(_translate("MainWindow", "0"))
        self.zero0.setText(_translate("MainWindow", "0"))
        self.ButtonEqual.setText(_translate("MainWindow", "="))
        self.batn1.setText(_translate("MainWindow", "1"))
        self.number2.setText(_translate("MainWindow", "2"))
        self.number3.setText(_translate("MainWindow", "3"))
        self.number4.setText(_translate("MainWindow", "4"))
        self.number5.setText(_translate("MainWindow", "5"))
        self.number6.setText(_translate("MainWindow", "6"))
        self.number7.setText(_translate("MainWindow", "7"))
        self.number8.setText(_translate("MainWindow", "8"))
        self.number9.setText(_translate("MainWindow", "9"))
        self.add.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.multy.setText(_translate("MainWindow", "*"))
        self.div.setText(_translate("MainWindow", "/"))

    def addFafunction(self):
      self.zero0.cliked.connect(lambda.selfwrite_number(self.zero0.text()))
      self.batn1.cliked.connect(lambda.selfwrite_number(self.batn1.text()))
      self.number2.cliked.connect(lambda.selfwrite_number(self.number2.text()))
      self.number3.cliked.connect(lambda.selfwrite_number(self.number3.text()))
      self.number4.cliked.connect(lambda.selfwrite_number(self.number4.text()))
      self.number5.cliked.connect(lambda.selfwrite_number(self.number5.text()))
      self.number6.cliked.connect(lambda.selfwrite_number(self.number6.text()))
      self.number7.cliked.connect(lambda.selfwrite_number(self.number7.text()))
      self.number8.cliked.connect(lambda.selfwrite_number(self.number8.text()))
      self.number9.cliked.connect(lambda.selfwrite_number(self.number9.text()))
      self.add.cliked.connect(lambda.selfwrite_number(self.add.text()))
      self.minus.cliked.connect(lambda.selfwrite_number(self.minus.text()))
      self.multy.cliked.connect(lambda.selfwrite_number(self.multy.text()))
      self.div.cliked.connect(lambda.selfwrite_number(self.div.text()))




   def write_number(self,number):
     print(number)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
